name: sankey
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - flask=2.0.1
  - psycopg2=2.9.1
  - pytest=6.2.5
  - werkzeug>=2.0.1
  - dask
  - distributed
  - python-dotenv
  - pyarrow
  - fastparquet
  - pip:
      - -r requirements.txt